services:
  web-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./storage
        target: /app/storage
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
