version: '3.8'

services:
  web-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - storage_data:/app/storage
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  storage_data:
